
final List<Map<String, String>> members = [
  {
    "name": "Asif",
    "phoneNumber": "8086 123 655",
    "district": "Malappuram",
    "panchayath": "Oorakam",
    "unit": "Oorakam Unit",
    "age": "26",
    "bloodGroup": "AB+ve",
    "status": "Unpaid",
  },
  {
    "name": "Noushad",
    "phoneNumber": "8086 123 655",
    "district": "Kozhikode",
    "panchayath": "Kappad",
    "unit": "Kappad Unit",
    "age": "30",
    "bloodGroup": "O+ve",
    "status": "Registered",
  },
  {
    "name": "Ameen",
    "phoneNumber": "8086 123 655",
    "district": "Kannur",
    "panchayath": "Thalassery",
    "unit": "Thalassery Unit",
    "age": "24",
    "bloodGroup": "B-ve",
    "status": "Unpaid",
  },
  {
    "name": "Haseeb",
    "phoneNumber": "8086 123 655",
    "district": "Thrissur",
    "panchayath": "Irinjalakuda",
    "unit": "Irinjalakuda Unit",
    "age": "29",
    "bloodGroup": "A+ve",
    "status": "Registered",
  },
  {
    "name": "Ameen",
    "phoneNumber": "8086 123 655",
    "district": "Palakkad",
    "panchayath": "Mannarkkad",
    "unit": "Mannarkkad Unit",
    "age": "28",
    "bloodGroup": "O+ve",
    "status": "Unpaid",
  },
];
